name: Convert and Push to Clash

on:
  push:
    paths:
      - "rules/*.list"
      - "scripts/list_to_clash.py"
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  convert_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Surge repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run list to YAML converter
        run: |
          pip install pyyaml
          python scripts/list_to_clash.py

      - name: Checkout Clash repo
        uses: actions/checkout@v3
        with:
          repository: LeiyuG/Clash
          token: ${{ secrets.CLASH_PUSH_TOKEN }
